config/routes.rb
RentalKoolicar::Application.routes.draw do
  resources :rentals

  root "home#index"
  get "/home" => "home#index"
  
end

app/models/rental.rb
require 'csv'
require 'net/http'
class Rental < ActiveRecord::Base
  mount_uploader :input_file, RentalUploader

  ## [{start: [lat, long], end: [lat, long]}, {start: [lat, long], ...}, ... ] ##
  serialize :positions, Array

  validates :name, :input_file,  presence: true

  # Redefine speed getter to round values
  def speed
    self[:speed].round(2) if !self[:speed].nil?
  end

  # Redefine mileage getter to round values
  def mileage
    self[:mileage].round(3) if !self[:mileage].nil?
  end

  def calculate_mileage
    begin
      ## Variables initialization ##
      start_pos = [nil, nil] ## [latitude, longitude]
      end_pos = [nil, nil]   ## [latitude, longitude]
      start_time = nil
      end_time = nil
      distance_in_meters = 0
      row_number = 1
      line_count = CSV.read(self.input_file.path, col_sep:";").count

      ## Browse CSV file line by line : ##
      ## calculate mileage and duration ##
      if line_count >= 2
        CSV.foreach(self.input_file.path, col_sep:";") do |timestamp, latitude, longitude|

          ## Set start_time (first timestamp) and end_time (last one) ##
          ## to calculate duration ##
          if row_number == 1
            start_time = Time.at(timestamp.to_i)
          elsif row_number == line_count
            end_time = Time.at(timestamp.to_i)
          end

          ## Calculate mileage
          if row_number == 1
            ## First line : init start positions ('latitude' and 'longitude') ##
            start_pos = [latitude.gsub(/\s+/, "").to_f, longitude.gsub(/\s+/, "").to_f]

          elsif row_number <= line_count
            ## 2nd line & other : set end positions ('latitude' and 'longitude') ##
            end_pos = [latitude.gsub(/\s+/, "").to_f, longitude.gsub(/\s+/, "").to_f]

            ## Save positions avoiding duplicates (When the vehicle has not moved) ##
            if start_pos != end_pos
              self.positions.push({start: start_pos, end: end_pos})
            end

            ## End positions becomes start positions for next line ##
            start_pos = end_pos.dup
            end_pos = nil

          end
          row_number += 1
        end

        if !start_time.nil? and !end_time.nil? and end_time > start_time
          self.duration = TimeDifference.between(start_time, end_time).humanize
        end

        ## Calculate total distance in meters point by point (accuracy purpose) ##
        distance_in_meters = self.calculate_total_distance

        ## Set mileage (in kilometers) ##
        self.mileage = distance_in_meters.to_f/1000.0
        ## Set average speed (kilometers by hour) ##
        self.speed = self.mileage.to_f/TimeDifference.between(start_time, end_time).in_hours.to_f
      end

      self.number = self.id
      self.save
    rescue => e
      raise StandardError.new("Problem during proces, possible reason : #{e}")
    end
  end

  ## Retrieve the total distance in meter from rental positions,             ## 
  ## segment by segment (accuracy purpose) with Goole Distance Matrix API    ##
  def calculate_total_distance
    ## Variables initialization ##
    query = ""
    threads = []
    urls = []
    queries = []
    total_distance_in_meters = 0
    corrected_points = []
    start_pos = []
    end_pos = []
    points_number_in_query = 0

    ###############################
    ####### 'Roads API' part ######
    ###############################

    ## Construct query for 'Roads API' requests ##
    self.positions.each_with_index do |segment, i|
      query += "#{segment[:start][0]},#{segment[:start][1]}|#{segment[:end][0]},#{segment[:end][1]}|"
      points_number_in_query += 2 ## Two points : start and end ##

      ## 'Roads API' constraint : no more thant 100 points by request ##
      if points_number_in_query == 100 or i == ((self.positions.length) -1)
        queries.push(query)
        query = ""
        points_number_in_query = 0
      end
    end
    
    ## Call 'Roads API' to refine the path by correcting the points coordinates ##
    queries.each do |query|
      encoded_url = URI.encode("https://roads.googleapis.com/v1/snapToRoads?path="+query[0..-2]+"&key=AIzaSyD-fOHs4K0jYCyJS03uG1mEKl-pDox0Bv8")
      uri = URI.parse(encoded_url)
      req = Net::HTTP::Get.new(uri.request_uri)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = (uri.scheme == "https")
      response = JSON.parse(http.request(req).body)

      ## Retrieve corrected coordinates from the JSON response ##
      response["snappedPoints"].each_with_index do |snapped_point, i|
        corrected_point_lat = snapped_point["location"]["latitude"]
        corrected_point_long = snapped_point["location"]["longitude"]

        if i == 0
          start_pos = [corrected_point_lat, corrected_point_long]
        else
          end_pos = [corrected_point_lat, corrected_point_long]
          if start_pos != end_pos
            ## Save them in
            corrected_points.push({start: start_pos, end: end_pos})
          end
          start_pos = end_pos.dup
          end_pos = nil
        end
      end
    end

    ################################
    ## 'Matrix Distance API' part ##
    ################################

    ## Compute URL list from positions data ##
    corrected_points.each do |segment|
      origin = segment[:start]
      destination = segment[:end]

      urls.push "https://maps.googleapis.com/maps/api/distancematrix/json?mode=driving&units=metric&origins=#{origin[0]},#{origin[1]}&destinations=#{destination[0]},#{destination[1]}&key=AIzaSyD-fOHs4K0jYCyJS03uG1mEKl-pDox0Bv8"
    end

    ## Call google api "Matrix Distance" for each segment ##
    urls.each do |url|
      ## Use Thread to "imitate" asynchronous request ##
      threads << Thread.new do
        uri = URI.parse(url)
        req = Net::HTTP::Get.new(uri.request_uri)
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = (uri.scheme == "https")
        response = JSON.parse(http.request(req).body)

        ## Extract the distance value in meter from the JSON structure ##
        segment_distance = response["rows"].first["elements"].first["distance"]["value"].to_i
        total_distance_in_meters += segment_distance.to_f
      end

      ## Wait for threads to finish before ending program ##
      threads.each { |t| t.join }
    end

    ##  Return the distance ##
    return total_distance_in_meters
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  def index
    @rentals = Rental.all
  end

  def show
    @rentals = Rental.find(params[:id])
  end

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        @rental.calculate_mileage
        format.html { redirect_to @rental, notice: "Rental was successfully created, the distance is : #{@rental.mileage}" }
        format.json { render action: 'show', status: :created, location: @rental }
      else
        format.html { render action: 'new' }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    def rental_params
      params.require(:rental).permit(:name, :input_file)
    end
end

app/views/home/index.html.erb
<div class="panel panel-default">
  <h2 class="panel-heading"> Welcome on board !</h2>
  <div class = "panel-body">
    <p class ="col-sm-12 ">
      This application allow you to calculate the distance traveled during a rental. <br>
      You simply need to upload positions (CSV format) of the journey, and that's it ! <br>
      You will also be able to display old rentals with their mileage, duration and speed.<br><br>
      Enjoy it !
    <p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rental Koolicar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

  <header class="col-md-12">
    <%# image_tag("logo_koolicar.jpg", class: "col-md-3", :alt => "rss feed", :width => "25%") %>
    <h1>Rental manager</h1>
    <hr>
  </header>

  <nav class="col-md-2">
    <ul class="nav nav-pills nav-stacked">
      <li><a href="/home"><i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;Home</a></li>
      <li><a href="/rentals/new"><i class="glyphicon glyphicon-plus"></i>&nbsp;&nbsp;New rental</a></li>
      <li><a href="/rentals"><i class="glyphicon glyphicon-th-list"></i>&nbsp;&nbsp;Rentals list</a></li>
    </ul>
  </nav>

  <section class="col-md-10">
    <%= yield %>
  </section>

  <footer class="col-md-12 well well-sm">
    <span class="col-md-4 text-left">Thibault Martin</span>
    <span class="col-md-4 text-center">Test technique - Koolicar</span>
    <span class="col-md-4 text-right">10/08/2017</span>
  </footer>

</body>
</html>

app/views/rentals/_form.html.erb
<%= form_for @rental, :html => {:class => "form-horizontal"} do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="col-sm-2 control-label">Rental name* :</label>
    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: 'Enter location name...', required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Update</button>
      <%= link_to 'Back', rentals_path, class:"btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/rentals/edit.html.erb
<div class="panel panel-default">
  <h2 class="panel-heading">Editing rental</h2>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/rentals/index.html.erb
<div class="panel panel-default">
  <h2 class="panel-heading">Rentals list</h2>
  <table class="table table-hover table-bordered panel-body">
    <thead >
      <tr>
        <th>Number</th>
        <th>Name</th>
        <th>Mileage (km)</th>
        <th>Duration</th>
        <th>Average speed (km/h)</th>
        <th>Updated_at</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @rentals.each do |rental| %>
        <tr>
          <td><%= rental.number %></td>
          <td><%= rental.name %></td>
          <td><%= rental.mileage %></td>
          <td><%= rental.duration %></td>
          <td><%= rental.speed %></td>
          <td><%= rental.updated_at.strftime("%Y-%m-%d : %H:%M:%S") %></td>
          <td>
            <span class="showIcon">
              <%= link_to rental, title: 'View', rel: 'tooltip' do %>
                  <i class="glyphicon glyphicon-eye-open"></i>
              <% end %>
            </span>

            <span class="editIcon">
              <%= link_to edit_rental_path(rental), title: 'Edit', rel: 'tooltip' do %>
                  <i class="glyphicon glyphicon-edit"></i>
              <% end %>
            </span>

            <span class="deleteIcon">
              <%= link_to rental, method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete', rel: 'tooltip' do %>
                  <i class="glyphicon glyphicon-trash"></i>
              <% end %>
            </span>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rentals/new.html.erb
<div class="panel panel-default">
  <h2 class="panel-heading">Create a rental</h2>

  <%= form_for @rental, :html => {:class => "form-horizontal"}, url: {action: "create"} do |f| %>
    <div class="panel-body">
      <div class="form-group">
        <label class="col-sm-2 control-label">Rental name* :</label>
        <div class="col-sm-10">
          <%= f.text_field :name, placeholder: 'Enter location name...', required: true, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">File input*</label>
        <div class="col-sm-10">
          <%= f.file_field :input_file, required: true, type: "file", id: "exampleInputFile" %>
          <p class="help-block">Select postions (csv)</p>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" id="submitButtonID" class="btn btn-primary">Calculate</button>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/rentals/show.html.erb
<div class="panel panel-default">
  <h2 class="panel-heading">Rental page</h2>

  <div class="panel-body">
    <p id="notice"><%= notice %></p>

    <div class="form-horizontal">
      <div class="form-group">
        <label class="control-label col-sm-2" >Number:</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @rental.number %></p>
        </div>
        <label class="control-label col-sm-2" >Name:</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @rental.name %></p>
        </div>
        <label class="control-label col-sm-2" >Mileage:</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @rental.mileage %></p>
        </div>
        <label class="control-label col-sm-2" >Duration:</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @rental.duration %></p>
        </div>
        <label class="control-label col-sm-2" >Speed:</label>
        <div class="col-sm-10">
          <p class="form-control-static"><%= @rental.speed %></p>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-11">
          <%= link_to 'Edit', edit_rental_path(@rental), class:"btn btn-primary" %>
          <%= link_to 'Back', rentals_path, class:"btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</div>